FinanceData/FinanceDataReader: Financial data reader

In [1]:
# FinanceData 설치
# !pip install finance-datareader

In [2]:
# 라이브러리 불러오기
import FinanceDataReader as fdr

In [3]:
# 버전확인
fdr.__version__

'0.9.94'

#### 한국거래소 상장종목 전체 가져오기

In [4]:
dir(fdr)

['DataReader',
 'EtfListing',
 'SnapDataReader',
 'StockListing',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_utils',
 'chart',
 'data',
 'ecos',
 'fred',
 'investing',
 'krx',
 'nasdaq',
 'naver',
 'plot',
 'wikipedia',
 'yahoo']

In [5]:
fdr.StockListing?

Signature: fdr.StockListing(market: str, start=None, end=None) -> pandas.core.frame.DataFrame
Docstring:
read stock list of stock exchanges
* market: 'KRX', 'KOSPI', 'KOSDAQ', 'KONEX', 'KRX-MARCAP',
        'KRX-DESC', 'KOSPI-DESC', 'KOSDAQ-DESC', 'KONEX-DESC',
        'KRX-DELISTING', 'KRX-ADMINISTRATIVE', 'KRX-MARCAP',
        'NASDAQ', 'NYSE', 'AMEX', 'SSE', 'SZSE', 'HKEX', 'TSE', 'HOSE',
        'S&P500',
        'ETF/KR',
File:      d:\kdt_2\anaconda3\lib\site-packages\financedatareader\data.py
Type:      function

In [6]:
stocks = fdr.StockListing('KRX')
stocks_desc = fdr.StockListing('KRX-DESC')

In [7]:
stocks.shape, stocks_desc.shape

((2856, 17), (2856, 10))

In [8]:
stocks.head()

,Code,ISU_CD,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId
0,005930,KR7005930003,삼성전자,KOSPI,,53700,1,600,1.13,53200,54400,53200,23588277,1270914173744,320577322935000,5969782550,STK
1,000660,KR7000660001,SK하이닉스,KOSPI,,173000,1,5000,2.98,170000,175600,169300,4671438,809096221721,125944409145000,728002365,STK
2,373220,KR7373220003,LG에너지솔루션,KOSPI,,382000,2,-7000,-1.80,389000,395000,382000,170616,66089934000,89388000000000,234000000,STK
3,207940,KR7207940008,삼성바이오로직스,KOSPI,,964000,1,3000,0.31,964000,981000,963000,47093,45667431000,68611736000000,71174000,STK
4,005380,KR7005380001,현대차,KOSPI,,204500,2,-4500,-2.15,209000,210500,204000,604002,124537800246,42825611059500,209416191,STK

In [9]:
stocks_desc.head()

,Code,Name,Market,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,060310,3S,KOSDAQ,"측정, 시험, 항해, 제어 및 기타 정밀기기 제조업; 광학기기 제외",반도체 웨이퍼 캐리어,2002-04-23,03월,김세완,http://www.3sref.com,서울특별시
1,095570,AJ네트웍스,KOSPI,산업용 기계 및 장비 임대업,"렌탈(파렛트, OA장비, 건설장비)",2015-08-21,12월,손삼달,http://www.ajnet.co.kr,서울특별시
2,006840,AK홀딩스,KOSPI,기타 금융업,지주사업,1999-08-11,12월,채형석,http://www.aekyunggroup.co.kr,서울특별시
3,054620,APS,KOSDAQ,기타 금융업,인터넷 트래픽 솔루션,2001-12-04,12월,정기로,http://www.apsholdings.co.kr,경기도
4,265520,AP시스템,KOSDAQ,특수 목적용 기계 제조업,디스플레이 제조 장비,2017-04-07,12월,김영주,http://www.apsystems.co.kr,경기도

In [10]:
stocks.columns

Index(['Code', 'ISU_CD', 'Name', 'Market', 'Dept', 'Close', 'ChangeCode',
       'Changes', 'ChagesRatio', 'Open', 'High', 'Low', 'Volume', 'Amount',
       'Marcap', 'Stocks', 'MarketId'],
      dtype='object')

In [11]:
stocks_columns = ['Code', 'Name', 'Market', 'Dept','Close', 'ChangeCode','Changes', 'ChagesRatio', 'Open', 'High', 'Low', 'Volume', 'Amount',
       'Marcap', 'Stocks', 'MarketId']

In [12]:
stocks_desc_columns = ['Code', 'Sector', 'Industry', 'ListingDate','SettleMonth', 'Representative', 'HomePage', 'Region']

In [13]:
stocks = stocks[stocks_columns]

In [14]:
stocks_desc = stocks_desc[stocks_desc_columns]

In [15]:
import numpy as np
import pandas as pd

In [16]:
#stocks join stocks_desc
new_stocks = pd.merge(stocks,stocks_desc,on='Code')

In [17]:
new_stocks.shape

(2856, 23)

In [18]:
new_stocks.columns

Index(['Code', 'Name', 'Market', 'Dept', 'Close', 'ChangeCode', 'Changes',
       'ChagesRatio', 'Open', 'High', 'Low', 'Volume', 'Amount', 'Marcap',
       'Stocks', 'MarketId', 'Sector', 'Industry', 'ListingDate',
       'SettleMonth', 'Representative', 'HomePage', 'Region'],
      dtype='object')

In [19]:
new_stocks.head()

,Code,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,...,Marcap,Stocks,MarketId,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,005930,삼성전자,KOSPI,,53700,1,600,1.13,53200,54400,...,320577322935000,5969782550,STK,통신 및 방송 장비 제조업,"통신 및 방송 장비 제조(무선) 제품, 반도체 제조(메모리) 제품, 전자부품 제조(...",1975-06-11,12월,한종희,http://www.samsung.com/sec,경기도
1,000660,SK하이닉스,KOSPI,,173000,1,5000,2.98,170000,175600,...,125944409145000,728002365,STK,반도체 제조업,"반도체,컴퓨터,통신기기 제조,도매",1996-12-26,12월,곽노정,http://www.skhynix.com,경기도
2,373220,LG에너지솔루션,KOSPI,,382000,2,-7000,-1.80,389000,395000,...,89388000000000,234000000,STK,일차전지 및 이차전지 제조업,"2차전지 (소형,ESS,자동차전지)",2022-01-27,12월,김동명,NaN,서울특별시
3,207940,삼성바이오로직스,KOSPI,,964000,1,3000,0.31,964000,981000,...,68611736000000,71174000,STK,기초 의약물질 제조업,바이오의약품,2016-11-10,12월,임존종보 (Rim John Chongbo),http://www.samsungbiologics.com,인천광역시
4,005380,현대차,KOSPI,,204500,2,-4500,-2.15,209000,210500,...,42825611059500,209416191,STK,자동차용 엔진 및 자동차 제조업,"자동차(승용차,버스,트럭,특장차),자동차부품,자동차전착도료 제조,차량정비사업",1974-06-28,12월,"정의선, 장재훈, 이동석(각자 대표이사)",http://www.hyundai.com,서울특별시

In [20]:
# 엑셀로 저장하기
new_stocks.to_excel('stocks.xlsx',index=False)