In [1]:
# 데이터 분석 패키지
import numpy as np
import pandas as pd

In [2]:
# 모든 컬럼을 출력하도록 설정
pd.set_option('display.max_columns', None)  # None으로 설정하면 모든 컬럼 출력
# 모든 행을 출력하도록 설정
pd.set_option('display.max_rows', 50)  # None으로 설정하면 모든 행 출력

In [3]:
df_stocks = pd.read_csv('stocks.csv')

In [4]:
df_stocks.head(1)

,Code,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,005930,삼성전자,KOSPI,NaN,54200,1,100,0.18,53500,54600,53300,12626235,680246198500,323562214210000,5969782550,STK,통신 및 방송 장비 제조업,"통신 및 방송 장비 제조(무선) 제품, 반도체 제조(메모리) 제품, 전자부품 제조(...",1975-06-11,12월,한종희,http://www.samsung.com/sec,경기도

In [11]:
df_stocks.index[df_stocks['ChagesRatio'] == 30]

Index([1232, 2018], dtype='int64')

#### 행추출 방법

In [12]:
# 행추출 방법
# 1. [] : 대괄호 접근
# df_stocks[df_stocks['ChagesRatio'] == 30]
# 2. loc : 인덱스명
# df_stocks.loc[df_stocks['ChagesRatio'] == 30]
# 3. iloc : 인덱스번호
indices = df_stocks.index[df_stocks['ChagesRatio'] == 30]
df_stocks.iloc[indices]
# 4. query
# df_stocks.query('ChagesRatio == 30')

,Code,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
1232,050960,수산아이앤티,KOSDAQ,벤처기업부,15860,4,3660,30.0,11000,15860,10640,950437,13732652520,107070860000,6751000,KSQ,소프트웨어 개발 및 공급업,"공유단말접속관리서비스, 보안솔루션 등",2016-10-11,12월,정은아,http://www.soosanint.co.kr,서울특별시
2018,121850,코이즈,KOSDAQ,벤처기업부,1495,4,345,30.0,1140,1495,1067,4923010,6886680301,45768191625,30614175,KSQ,플라스틱제품 제조업,"보호필름, 도광판, 백코팅",2012-09-27,12월,조재형,http://www.koyj.co.kr,충청북도

#### 행을 추출한뒤 열을 추출방법

In [32]:
# 1. [] : 대괄호 접근
# df_stocks[df_stocks['ChagesRatio'] == 30][['Name','Sector']]
# 2. loc : 인덱스명
# df_stocks.loc[df_stocks['ChagesRatio'] == 30][['Name','Sector']]
# df_stocks.loc[df_stocks['ChagesRatio'] == 30,['Name','Sector']]
# 3. iloc : 인덱스번호
# indices = df_stocks.index[df_stocks['ChagesRatio'] == 30]
# df_stocks.iloc[indices]
# df_stocks.iloc[df_stocks.index[df_stocks['ChagesRatio'] == 30]][['Name','Sector']]
# df_stocks.iloc[df_stocks.index[df_stocks['ChagesRatio'] == 30], [1,16]]
# 4. query
df_stocks.query('ChagesRatio == 30')[['Name','Sector']]

        Name          Sector
1232  수산아이앤티  소프트웨어 개발 및 공급업
2018     코이즈      플라스틱제품 제조업

In [8]:
df_stocks.describe()

,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks
count,2.856000e+03,2856.000000,2856.000000,2856.000000,2.856000e+03,2.856000e+03,2.856000e+03,2.856000e+03,2.856000e+03,2.856000e+03,2.856000e+03
mean,1.727781e+04,1.741597,-252.238095,-1.340434,1.735008e+04,1.772746e+04,1.658957e+04,5.309359e+05,6.083786e+09,8.130226e+11,4.186027e+07
std,5.555771e+04,0.618823,3615.763860,3.899823,5.960333e+04,6.369783e+04,5.402176e+04,2.191040e+06,3.565241e+10,7.277021e+12,1.327892e+08
min,3.000000e+00,0.000000,-187000.000000,-29.930000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.180000e+07,2.000000e+05
25%,2.078750e+03,1.000000,-200.000000,-3.060000,2.000000e+03,2.015000e+03,1.970750e+03,2.497900e+04,1.015650e+08,4.137168e+10,1.017354e+07
50%,4.800000e+03,2.000000,-50.000000,-1.280000,4.677500e+03,4.797500e+03,4.445000e+03,9.306500e+04,4.239842e+08,8.954548e+10,1.977295e+07
75%,1.277500e+04,2.000000,0.000000,0.000000,1.266750e+04,1.288250e+04,1.211000e+04,2.738850e+05,1.842106e+09,2.277213e+11,4.189457e+07
max,1.813000e+06,5.000000,8800.000000,30.000000,2.124000e+06,2.407000e+06,1.736000e+06,3.784488e+07,1.228937e+12,3.229652e+14,5.969783e+09

In [35]:
# 전일 대비 상승률 상위 30위 종목
top_30_increse_indices =df_stocks.sort_values('ChagesRatio',ascending=False).head(30).index
df_top_30_increse = df_stocks.iloc[top_30_increse_indices]
df_top_30_increse

,Code,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
2085,139670,키네마스터,KOSDAQ,중견기업부,3120,4,720,30.00,2565,3120,2565,3129373,9360216870,44050687200,14118810,KSQ,소프트웨어 개발 및 공급업,"NexMFW, NexPlayer EMB",2011-12-02,12월,"홍기태, 송광은(공동대표)",http://www.kinemastercorp.com,서울특별시
2608,030350,드래곤플라이,KOSDAQ,중견기업부,1244,4,287,29.99,957,1244,859,2794818,3192398685,17263975736,13877794,KSQ,소프트웨어 개발 및 공급업,온라인게임,1997-11-10,12월,조 철,http://www.dragonflygame.com,서울특별시
1856,015020,이스타코,KOSPI,NaN,1301,4,300,29.97,960,1301,910,13274549,15869422663,55749931600,42851600,STK,부동산 임대 및 공급업,부동산 분양/입시학원 운영,1988-12-23,12월,"김승제,김동현(각자대표)",http://www.e-starco.co.kr,서울특별시
1371,383930,디티앤씨알오,KOSDAQ,중견기업부,7480,4,1720,29.86,5790,7480,5790,3985334,28777422410,95523429760,12770512,KSQ,자연과학 및 공학 연구개발업,비임상 및 임상시험 대체 용역,2022-11-11,12월,박채규,http://www.dtncro.com,경기도
1552,065500,오리엔트정공,KOSDAQ,중견기업부,2480,4,569,29.77,2270,2480,2150,16045192,37581210682,78722421760,31742912,KSQ,자동차 신품 부품 제조업,"하우징, 리테이너베어링",2002-09-19,12월,"장재진, 박영동",http://www.orientpi.co.kr,경상북도
492,025950,동신건설,KOSDAQ,우량기업부,44050,1,8800,24.96,36400,45800,34150,5292157,220909453650,370020000000,8400000,KSQ,토목 건설업,토목,1995-08-07,12월,"김근한,김동한",http://www.dongsin.biz,경상북도
1566,020710,시공테크,KOSDAQ,우량기업부,3880,1,715,22.59,3175,4090,3175,1522536,5787089095,77786123600,20047970,KSQ,전문디자인업,"박물관, 전시관, 엑스포, 특수영상",1999-08-13,12월,김승태,http://www.sigongtech.co.kr,경기도
2563,004105,태양금속우,KOSPI,NaN,5980,1,1070,21.79,4880,6380,4855,1997758,11904641400,19734000000,3300000,STK,NaN,NaN,NaN,NaN,NaN,NaN,NaN
982,013360,일성건설,KOSPI,NaN,2785,1,485,21.09,2295,2950,2000,27641703,73759289410,150459290800,54024880,STK,토목 건설업,"건축공사,토목공사,전기공사",1989-12-02,12월,유필상,http://www.ilsungconst.co.kr,경기도
670,045660,에이텍,KOSDAQ,우량기업부,29500,1,5100,20.90,23450,31550,22000,7527659,216287528800,243670000000,8260000,KSQ,컴퓨터 및 주변장치 제조업,"PC,모니터",2001-05-24,12월,"신승영, 이상훈(각자 대표이사)",http://www.atec.kr,경기도
2255,121850,코이즈,KOSDAQ,벤처기업부,1150,1,195,20.42,1002,1217,951,5866858,6543370315,35206301250,30614175,KSQ,플라스틱제품 제조업,"보호필름, 도광판, 백코팅",2012-09-27,12월,조재형,http://www.koyj.co.kr,충청북도
1623,045340,토탈소프트,KOSDAQ,벤처기업부,8600,1,1440,20.11,6970,9000,6320,3159671,25712220910,73599144000,8558040,KSQ,소프트웨어 개발 및 공급업,해운물류소프트웨어 (CATOS 등),2002-07-19,12월,최장수,http://www.tsb.co.kr,부산광역시
2358,065770,CS,KOSDAQ,벤처기업부,1549,1,256,19.80,1300,1680,1150,8582656,12933839239,30067840370,19411130,KSQ,통신 및 방송 장비 제조업,"이동통신중계기, 위성방송(DMB)중계기(Gap-Filler)",2004-06-04,12월,최규훈,http://www.cs-holdings.co.kr,경기도
1508,050960,수산아이앤티,KOSDAQ,벤처기업부,12200,1,1890,18.33,9920,13040,9290,1161767,13658523330,82362200000,6751000,KSQ,소프트웨어 개발 및 공급업,"공유단말접속관리서비스, 보안솔루션 등",2016-10-11,12월,정은아,http://www.soosanint.co.kr,서울특별시
1186,224110,에이텍모빌리티,KOSDAQ,중견기업부,21800,1,3310,17.90,17500,23700,16660,4303935,91910409210,116412000000,5340000,KSQ,통신 및 방송 장비 제조업,교통카드단말기,2015-08-25,12월,"신승영, 최성용(각자대표이사)",http://www.atecmobility.com,경기도
1412,007720,대명소노시즌,KOSDAQ,중견기업부,906,1,133,17.21,982,1004,906,24049706,23343218993,91325207700,100800450,KSQ,상품 종합 도매업,기업소모성자재 구매대행업,1994-01-06,12월,권광수,http://sonoseason.com,강원특별자치도
1600,052220,iMBC,KOSDAQ,중견기업부,3285,1,460,16.28,2800,3485,2780,20553623,67003423005,75555000000,23000000,KSQ,영상·오디오물 제공 서비스업,"디지털콘텐츠,웹에이젼시",2005-01-21,12월,이선태,http://corp.imbc.com,서울특별시
472,084690,대상홀딩스,KOSPI,NaN,10930,1,1460,15.42,9590,11900,9370,13912098,155014442380,395803040340,36212538,STK,기타 금융업,지주회사,2005-08-17,12월,"임창욱, 최성수 각자대표이사",NaN,서울특별시
1851,093240,형지엘리트,KOSPI,NaN,1583,1,203,14.71,1380,1730,1355,37844885,60212596857,56123716826,35454022,STK,봉제의복 제조업,"학생복,스포츠의류,작업복 제조,도매",2009-09-28,06월,최준호,http://www.hyungji-elite.com,인천광역시
2822,266350,팡스카이,KONEX,일반기업부,523,1,67,14.69,456,523,388,1527,592679,4129111150,7895050,KNX,소프트웨어 개발 및 공급업,게임 개발 및 리퍼블리싱,2024-06-28,12월,"조호현, 이병진",http://www.panggame.com/,서울특별시
1088,173130,오파스넷,KOSDAQ,우량기업부,10120,1,1290,14.61,9170,11190,8900,14119477,145849865760,132030306760,13046473,KSQ,"컴퓨터 프로그래밍, 시스템 통합 및 관리업",네트워크 구축 및 유지보수,2018-08-24,12월,장수현,http://www.opasnet.co.kr,서울특별시
1183,033320,제이씨현시스템,KOSDAQ,우량기업부,6100,1,770,14.45,5620,6340,5480,33713416,202065317370,116598035200,19114432,KSQ,기계장비 및 관련 물품 도매업,"메인보드, 그래픽카드",1997-11-10,12월,"차중석, 차정헌",http://www.jchyun.com,서울특별시
2819,266870,파워풀엑스,KONEX,일반기업부,685,1,85,14.17,685,685,685,1,685,4389945800,6408680,KNX,기타 화학제품 제조업,플렉스파워 리커버리크림,2017-04-24,12월,박인철,http://www.flexpower.co.kr,서울특별시
1704,014990,인디에프,KOSPI,NaN,896,1,110,13.99,785,971,768,8152775,7257076059,67301243520,75112995,STK,봉제의복 제조업,"여성의류,남성의류,캐쥬얼웨어 제조",1989-06-20,12월,손수근,http://www.inthef.co.kr,서울특별시
1461,407400,꿈비,KOSDAQ,벤처기업부,7050,1,850,13.71,6200,7650,6200,2904288,20630445370,86429291700,12259474,KSQ,가구 제조업,"놀이방매트, 유아거실가구 등",2023-02-09,12월,박영건,http://ggumbi.com/,경기도
2245,286750,나노브릭,KOSDAQ,기술성장기업부,1719,1,206,13.62,1511,1724,1426,395233,613733654,35573946921,20694559,KSQ,기초 화학물질 제조업,"보안응용제품(M-tag 및 M-pac), 보안소재제품(M-secuprint)",2019-08-19,12월,주재현,http://www.nanobrick.co.kr,경기도
2078,016920,카스,KOSDAQ,중견기업부,1679,1,198,13.37,1464,1849,1347,9839431,16677059955,44482650302,26493538,KSQ,기계장비 및 관련 물품 도매업,"전자저울,로드셀",1990-01-04,12월,김태인,http://www.cas.co.kr,경기도
2548,084695,대상홀딩스우,KOSPI,NaN,22700,1,2650,13.22,19710,24300,19710,118630,2751260600,20736041400,913482,STK,NaN,NaN,NaN,NaN,NaN,NaN,NaN
553,052400,코나아이,KOSDAQ,우량기업부,21000,1,2370,12.72,18150,23150,17200,2662052,56305230000,312899979000,14899999,KSQ,소프트웨어 개발 및 공급업,"전자화폐, 단말기, 수집/정산시스템",2001-10-18,12월,조정일,http://konai.com,서울특별시
2528,009620,삼보산업,KOSDAQ,중견기업부,1475,1,166,12.68,1309,1658,1200,1625073,2323508090,21766840500,14757180,KSQ,1차 비철금속 제조업,알미늄괴,1993-12-07,12월,"이태용, 최재훈 (각자대표이사)",http://www.samboind.com,경상남도

In [36]:
# 전일 대비 상승률 하위 30위 종목
bottom_30_increse_indices =df_stocks.sort_values('ChagesRatio',ascending=True).head(30).index
df_bottom_30_increse = df_stocks.iloc[bottom_30_increse_indices]
df_bottom_30_increse

,Code,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
1205,294090,이오플로우,KOSDAQ,기술성장기업부,3770,5,-1610,-29.93,3770,4230,3770,14837824,57528627545,114742434430,30435659,KSQ,의료용 기기 제조업,웨어러블 인슐린펌프,2020-09-14,12월,김재진,http://www.eoflow.com,경기도
2855,419700,이브이파킹서비스,KONEX,일반기업부,3,2,-1,-25.00,4,4,2,2675272,7991664,51799998,17266666,KNX,기계장비 및 관련 물품 도매업,전기차 충전 솔루션 및 인프라,2023-07-05,12월,김정수,http://evps.co.kr/,서울특별시
2641,031860,에스유홀딩스,KOSDAQ,투자주의환기종목(소속부없음),1020,2,-255,-20.00,1275,1276,955,1177180,1202127359,15326883120,15026356,KSQ,상품 종합 도매업,FLC,1997-01-07,12월,이상욱 (단독대표),http://su-holdings.com,서울특별시
1800,006050,국영지앤엠,KOSDAQ,중견기업부,1718,2,-427,-19.91,2020,2100,1693,8858120,16598222259,59950027474,34895243,KSQ,유리 및 유리제품 제조업,강화유리,1994-10-07,12월,최재원,http://www.kukyong.com,서울특별시
833,321820,아티스트유나이티드,KOSDAQ,기술성장기업부,13590,2,-3340,-19.73,13000,14940,11860,3623702,47307295410,181654947900,13366810,KSQ,소프트웨어 개발 및 공급업,빅데이터/인공지능 마케팅플랫폼 및 데이터플랫폼,2021-02-03,12월,이태성,http://www.widerplanet.com,서울특별시
2448,025560,미래산업,KOSPI,NaN,822,2,-195,-19.17,809,843,803,5534418,4576423902,25619163030,31166865,STK,"측정, 시험, 항해, 제어 및 기타 정밀기기 제조업; 광학기기 제외","PCB마운터,반도체검사장비(반도체테스트핸들러),LCD 검사장비,리드프레임매가진 제조...",1996-11-22,12월,이창재,http://www.mirae.co.kr,충청남도
1685,024740,한일단조,KOSDAQ,중견기업부,2100,2,-395,-15.83,2370,2410,2065,7625733,16567717405,69083802900,32897049,KSQ,자동차 신품 부품 제조업,단조품,1996-11-29,12월,박정영,http://www.hifg.co.kr,충청북도
2828,002995,금호건설우,KOSPI,NaN,12900,2,-2300,-15.13,14300,14300,12900,25107,336977590,3770231400,292266,STK,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2784,116100,태양기계,KONEX,일반기업부,1226,5,-216,-14.98,1226,1637,1226,701,859837,7650222836,6239986,KNX,자동차 신품 부품 제조업,엔진부품,2013-07-01,12월,박창엽,http://www.sun-mc.co.kr,경기도
2806,092590,럭스피아,KONEX,일반기업부,807,5,-142,-14.96,807,999,807,1174,947610,5883916086,7291098,KNX,반도체 제조업,"LED 패키지, LED 모듈",2015-10-30,12월,성석종,http://www.luxpialed.com,경기도
2808,448780,마이크로엔엑스,KONEX,일반기업부,2025,5,-355,-14.92,2420,2420,2025,725,1468520,5422302000,2677680,KNX,의료용 기기 제조업,의료용구(전동기),2022-12-21,12월,이종건/정재경,http://www.micronx.co.kr,대구광역시
2674,178600,대동고려삼,KONEX,일반기업부,2975,5,-520,-14.88,2975,2975,2975,1,2975,13237560000,4449600,KNX,기타 식품 제조업,"인삼식품(홍삼진액, 홍삼정)",2013-12-20,06월,최 성 근,http://www.ddkorea.co.kr,충청남도
2638,223220,로지스몬,KONEX,일반기업부,340,5,-59,-14.79,340,340,340,100,34000,15657399840,46051176,KNX,기타 운송관련 서비스업,모바일 컨텐츠 개발 및 유통,2015-07-09,12월,이석준,http://ipmonster.co.kr,서울특별시
2409,354390,바스칸바이오제약,KONEX,일반기업부,3920,2,-675,-14.69,4315,4315,3910,3671,14481090,27511528240,7018247,KNX,의약품 제조업,"일반의약품, 전문의약품, 의료기기",2022-07-20,12월,이법표,http://www.baskhanbio.com,경기도
1541,465480,인스피언,KOSDAQ,벤처기업부,7830,2,-1340,-14.61,9140,9250,7610,560539,4609040130,79378754760,10137772,KSQ,소프트웨어 개발 및 공급업,"SAP 보안 솔루션, SAP PO/CPI 컨설팅, EDI SaaS 플랫폼",2024-10-18,12월,최정규,http://www.inspien.co.kr,서울특별시
1035,322310,오로스테크놀로지,KOSDAQ,벤처기업부,15100,2,-2430,-13.86,17000,17000,14720,554358,8677802550,141434784200,9366542,KSQ,특수 목적용 기계 제조업,반도체 Overlay 계측 장비,2021-02-24,12월,"각자 대표이사 이준우, 최성원",http://www.aurostech.com,경기도
559,216080,제테마,KOSDAQ,기술성장기업부,17330,2,-2720,-13.57,20500,20750,17120,485065,8963791940,310072848470,17892259,KSQ,의료용품 및 기타 의약 관련제품 제조업,"히알루론산 필러(조직수복용생체재료), 피부과용 레이저 의료기기, 리프팅실 등",2019-11-14,12월,"김재영, 남정선 (각자대표)",http://www.jetema.com,강원특별자치도
1848,308080,바이젠셀,KOSDAQ,기술성장기업부,2945,2,-445,-13.13,3730,3785,2880,2035165,6870332690,56731714300,19263740,KSQ,자연과학 및 공학 연구개발업,"면역세포치료제 (면역항암제, 면역조절치료제 등)",2021-08-25,12월,김태규,http://www.vigencell.com/kr/index.asp,서울특별시
916,206560,덱스터,KOSDAQ,기술성장기업부,6440,2,-960,-12.97,7270,7380,6360,891568,6040154740,163651579840,25411736,KSQ,"영화, 비디오물, 방송프로그램 제작 및 배급업","시각효과(Visual Effect, VFX)",2015-12-22,12월,"김욱, 강종익",http://www.dexterstudios.com,서울특별시
727,389020,자람테크놀로지,KOSDAQ,기술성장기업부,35700,2,-5100,-12.50,41700,41700,35300,659414,24585034350,221258961000,6197730,KSQ,반도체 제조업,"XGSPON, 기가와이어, 광트랜시버 등",2023-03-07,12월,백준현,http://zaram.com,경기도
624,037270,YG PLUS,KOSPI,NaN,4230,2,-600,-12.42,4800,4830,4215,4537476,20181735205,268306404300,63429410,STK,"자료처리, 호스팅, 포털 및 기타 인터넷 정보매개 서비스업","광고대행,광고물 제작",2003-08-01,12월,최성준,http://www.ygplus.com,서울특별시
1584,348350,위드텍,KOSDAQ,우량기업부,7520,2,-1030,-12.05,8410,8450,7520,198227,1553236510,76580672000,10183600,KSQ,"측정, 시험, 항해, 제어 및 기타 정밀기기 제조업; 광학기기 제외","AMCs 모니터링 시스템, 공정 프로세스 모니터링 시스템, TMS",2020-10-30,12월,"유승교,박현열(각자 대표이사)",http://www.withtech.co.kr,대전광역시
663,299900,위지윅스튜디오,KOSDAQ,우량기업부,1435,2,-196,-12.02,1560,1574,1370,4809167,6991992915,245455148540,171048884,KSQ,"영화, 비디오물, 방송프로그램 제작 및 배급업","VFX, 뉴미디어 등 특수영상 컨텐츠 제작",2018-12-20,12월,조성완,http://www.wswgstudios.com,서울특별시
2825,00781K,코리아써키트2우B,KOSPI,NaN,5000,2,-670,-11.82,5980,5980,5000,2909,15015550,3918495000,783699,STK,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1889,474610,RF시스템즈,KOSDAQ,벤처기업부,4280,2,-570,-11.75,4875,4970,4195,787184,3489641600,53851229640,12582063,KSQ,기타 금속 가공제품 제조업,"방산제품(레이더시스템, 안테나시스템, 환경제어시스템 등)",2024-11-19,12월,한기우,http://www.rf-systems.co.kr/,경기도
1509,457370,한켐,KOSDAQ,중견기업부,10250,2,-1350,-11.64,11310,11470,10180,559517,5975230600,82278123500,8027134,KSQ,기초 화학물질 제조업,OLED 발광층 소재 등,2024-10-22,12월,이상조,http://www.hanchem.net,대전광역시
1714,460470,아이빔테크놀로지,KOSDAQ,기술성장기업부,4410,2,-580,-11.62,4940,4975,4285,957013,4399354840,66522071700,15084370,KSQ,사진장비 및 광학기기 제조업,"생체현미경, CRO 서비스",2024-08-06,12월,김필한,http://www.ivimtech.com,대전광역시
2235,323350,다원넥스뷰,KOSDAQ,기술성장기업부,4520,2,-590,-11.55,5030,5030,4420,84109,385954145,36208689440,8010772,KSQ,사진장비 및 광학기기 제조업,LSMB(Laser Micro Bonding System),2024-06-11,12월,남기중,http://www.nexview.co.kr,경기도
1308,317690,퀀타매트릭스,KOSDAQ,기술성장기업부,6160,2,-780,-11.24,7260,7400,6120,1181950,7873296620,101870451760,16537411,KSQ,의료용 기기 제조업,신속항균제검사 장비 및 키트,2020-12-09,12월,권성훈,http://www.quantamatrix.com,서울특별시
468,334970,프레스티지바이오로직스,KOSDAQ,기술성장기업부,5160,2,-650,-11.19,5890,5890,5110,402485,2143170400,399475006920,77417637,KSQ,의약품 제조업,바이오시밀러 제조,2021-03-11,06월,현덕훈,http://www.prestigebiologics.com,충청북도

In [31]:
# 전일 대비 상승률 상위 30위 종목
# 업종
# df_top_30_increse['Sector'].value_counts()
df_bottom_30_increse['Sector'].value_counts()

Sector
의료용 기기 제조업                               3
자동차 신품 부품 제조업                            2
영화, 비디오물, 방송프로그램 제작 및 배급업                2
의약품 제조업                                  2
반도체 제조업                                  2
사진장비 및 광학기기 제조업                          2
측정, 시험, 항해, 제어 및 기타 정밀기기 제조업; 광학기기 제외    2
소프트웨어 개발 및 공급업                           2
기타 식품 제조업                                1
기계장비 및 관련 물품 도매업                         1
유리 및 유리제품 제조업                            1
특수 목적용 기계 제조업                            1
의료용품 및 기타 의약 관련제품 제조업                    1
자연과학 및 공학 연구개발업                          1
상품 종합 도매업                                1
자료처리, 호스팅, 포털 및 기타 인터넷 정보매개 서비스업         1
기타 금속 가공제품 제조업                           1
기초 화학물질 제조업                              1
기타 운송관련 서비스업                             1
Name: count, dtype: int64

In [101]:
df_stocks.index

RangeIndex(start=0, stop=2856, step=1)

In [98]:
df_stocks.groupby('Sector')[['Marcap']].idxmax()

                     Marcap
Sector
1차 비철금속 제조업               7
1차 철강 제조업                13
가구 제조업                  413
가전제품 및 정보통신장비 소매업       868
가정용 기기 제조업              140
...                     ...
항공기,우주선 및 부품 제조업         30
해상 운송업                   25
해체, 선별 및 원료 재생업        1927
화학섬유 제조업                248
회사 본부 및 경영 컨설팅 서비스업     294

[160 rows x 1 columns]

In [79]:
dir(df_stocks.groupby('Sector')['Marcap'])

['_SeriesGroupBy__examples_series_doc',
 '__annotations__',
 '__class__',
 '__class_getitem__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__orig_bases__',
 '__parameters__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_accessors',
 '_agg_examples_doc',
 '_agg_general',
 '_agg_py_fallback',
 '_aggregate_multiple_funcs',
 '_aggregate_named',
 '_aggregate_with_numba',
 '_apply_filter',
 '_ascending_count',
 '_concat_objects',
 '_constructor',
 '_cumcount_array',
 '_cython_agg_general',
 '_cython_transform',
 '_deprecate_axis',
 '_descending_count',
 '_dir_additions',
 '_dir_deletions',
 '_fill',
 '_get_data_to_aggregate',
 '_get_index',
 '_get_indices',
 '_gotitem',
 '_grouper',
 '_hidden_attrs',
 '_idxmax_idxmin',
 '_infer_selection',
 '_insert_inaxis_grouper',
 '_internal_names',
 '_internal_names_set',
 '_make_mask_from_int',
 '_make_mask_from_list',
 '_make_mask_from_positional_indexer',
 '_make_mask_from_slice',
 '_make_mask_from_tuple',
 '_mask_selected_obj',
 '_maybe_transpose_result',
 '_nth',
 '_numba_agg_general',
 '_numba_prep',
 '_obj_1d_constructor',
 '_obj_with_exclusions',
 '_op_via_apply',
 '_positional_selector',
 '_python_agg_general',
 '_python_apply_general',
 '_reindex_output',
 '_reset_cache',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_set_result_index_ordered',
 '_transform',
 '_transform_general',
 '_transform_with_numba',
 '_value_counts',
 '_wrap_agged_manager',
 '_wrap_aggregated_output',
 '_wrap_applied_output',
 '_wrap_idxmax_idxmin',
 '_wrap_transform_fast_result',
 'agg',
 'aggregate',
 'all',
 'any',
 'apply',
 'bfill',
 'corr',
 'count',
 'cov',
 'cumcount',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'dtype',
 'ewm',
 'expanding',
 'ffill',
 'fillna',
 'filter',
 'first',
 'get_group',
 'groups',
 'head',
 'hist',
 'idxmax',
 'idxmin',
 'indices',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'last',
 'max',
 'mean',
 'median',
 'min',
 'ndim',
 'ngroup',
 'ngroups',
 'nlargest',
 'nsmallest',
 'nth',
 'nunique',
 'ohlc',
 'pct_change',
 'pipe',
 'plot',
 'prod',
 'quantile',
 'rank',
 'resample',
 'rolling',
 'sample',
 'sem',
 'shift',
 'size',
 'skew',
 'std',
 'sum',
 'tail',
 'take',
 'transform',
 'unique',
 'value_counts',
 'var']

In [96]:
df_stocks.groupby('Sector')['Marcap'].sum()

Sector
1차 비철금속 제조업            42025679933262
1차 철강 제조업              36062504736190
가구 제조업                  1579352329179
가전제품 및 정보통신장비 소매업        173044528960
가정용 기기 제조업              3750559291419
                            ...
항공기,우주선 및 부품 제조업       20223759888903
해상 운송업                 18821548038885
해체, 선별 및 원료 재생업           52393434311
화학섬유 제조업                3602587510624
회사 본부 및 경영 컨설팅 서비스업     3497612924040
Name: Marcap, Length: 160, dtype: int64

In [62]:
df_stocks.groupby('Sector')['Marcap'].sum().reset_index()

                  Sector          Marcap
0            1차 비철금속 제조업  42025679933262
1              1차 철강 제조업  36062504736190
2                 가구 제조업   1579352329179
3      가전제품 및 정보통신장비 소매업    173044528960
4             가정용 기기 제조업   3750559291419
..                   ...             ...
155     항공기,우주선 및 부품 제조업  20223759888903
156               해상 운송업  18821548038885
157      해체, 선별 및 원료 재생업     52393434311
158             화학섬유 제조업   3602587510624
159  회사 본부 및 경영 컨설팅 서비스업   3497612924040

[160 rows x 2 columns]

In [67]:
df_stocks.groupby('Sector')['Marcap'].idxmax()

Sector
1차 비철금속 제조업               7
1차 철강 제조업                13
가구 제조업                  413
가전제품 및 정보통신장비 소매업       868
가정용 기기 제조업              140
                       ...
항공기,우주선 및 부품 제조업         30
해상 운송업                   25
해체, 선별 및 원료 재생업        1927
화학섬유 제조업                248
회사 본부 및 경영 컨설팅 서비스업     294
Name: Marcap, Length: 160, dtype: int64

In [60]:
# 산업별 시가총액 상위목록
print(df_stocks.columns)

# 산업별 시가 총액 합계 계산
grouped = df_stocks.groupby('Sector')['Marcap'].sum().reset_index()

# 각 산업별로 시가총액이 가장 높은 기업 찾기
top_industries = df_stocks.loc[df_stocks.groupby('Sector')['Marcap'].idxmax()]

top_industries

Index(['Code', 'Name', 'Market', 'Dept', 'Close', 'ChangeCode', 'Changes',
       'ChagesRatio', 'Open', 'High', 'Low', 'Volume', 'Amount', 'Marcap',
       'Stocks', 'MarketId', 'Sector', 'Industry', 'ListingDate',
       'SettleMonth', 'Representative', 'HomePage', 'Region'],
      dtype='object')

,Code,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
7,010130,고려아연,KOSPI,NaN,1813000,2,-187000,-9.35,2124000,2407000,1736000,248705,520852009000,37535052079000,20703283,STK,1차 비철금속 제조업,"연,아연괴 제조,판매",1990-07-28,12월,"박기덕, 정태웅",http://www.koreazinc.co.kr,서울특별시
13,005490,POSCO홀딩스,KOSPI,NaN,265500,2,-1000,-0.38,266500,270500,257000,464808,122727927500,21936772093500,82624377,STK,1차 철강 제조업,"열연코일,냉연강판,후판,선재,스테인리스 제조",1988-06-10,12월,"대표이사 회장 장인화, 대표이사 사장 정기섭",http://www.posco-inc.com,경상북도
413,013890,지누스,KOSPI,NaN,23100,1,1300,5.96,22200,23800,21900,347667,8013373900,468025219200,20260832,STK,가구 제조업,매트리스 및 가구제품,2019-10-30,12월,윤종원,http://www.zinus.co.kr,경기도
868,071840,롯데하이마트,KOSPI,NaN,7330,2,-100,-1.35,7360,7480,7090,45959,333161100,173044528960,23607712,STK,가전제품 및 정보통신장비 소매업,"가전제품,잡화 도소매/부동산 임대",2011-06-29,12월,남창희,http://company.himart.co.kr,서울특별시
140,065350,신성델타테크,KOSDAQ,우량기업부,74600,1,800,1.08,74100,79400,73000,634228,48251391600,2050302520800,27483948,KSQ,가정용 기기 제조업,"세탁기, 자동차, 에어컨 및 LCD 부품",2004-08-06,12월,구본상·이동한(각자 대표이사),http://www.ssdelta.co.kr,경상남도
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30,012450,한화에어로스페이스,KOSPI,NaN,298000,2,-10000,-3.25,314500,317500,286000,932726,276597954500,13583185978000,45581161,STK,"항공기,우주선 및 부품 제조업","항공기엔진,특수방산장비 제조/정비사업",1987-05-27,12월,"손재일, 김동관",http://www.hanwhaaerospace.co.kr/,경상남도
25,011200,HMM,KOSPI,NaN,18000,2,-210,-1.15,18220,18500,17750,1153122,20900707030,15858710928000,881039496,STK,해상 운송업,"정기,부정기,전용선,콘테이너선,자동차선,LNG선 해운",1995-10-05,12월,김경배,http://www.hmm21.com,서울특별시
1927,032860,더라미,KOSDAQ,투자주의환기종목(소속부없음),1297,2,-30,-2.26,1294,1330,1257,167150,215121823,52393434311,40395863,KSQ,"해체, 선별 및 원료 재생업","화장품, 철스크랩",1997-07-04,12월,현병택,http://www.thelamy.com,경기도
248,298020,효성티앤씨,KOSPI,NaN,218000,2,-2500,-1.13,222500,222500,212000,25907,5624492000,943434676000,4327682,STK,화학섬유 제조업,"섬유, 산업자재, 화학, 중공업, 건설, 무역,금융 등",2018-07-13,12월,김치형,http://www.hyosungtnc.com,서울특별시
294,036830,솔브레인홀딩스,KOSDAQ GLOBAL,우량기업부,35550,2,-400,-1.11,36250,37550,34850,112767,4068258300,745272190800,20964056,KSQ,회사 본부 및 경영 컨설팅 서비스업,"반도체,디스플레이,2차전지 공정용 화학제품",2000-01-18,12월,정현석,http://www.soulbrainholdings.co.kr,경기도