In [1]:
# 데이터 분석 패키지
import numpy as np
import pandas as pd

In [2]:
# 모든 컬럼을 출력하도록 설정
pd.set_option('display.max_columns', None)  # None으로 설정하면 모든 컬럼 출력
# 모든 행을 출력하도록 설정
pd.set_option('display.max_rows', 50)  # None으로 설정하면 모든 행 출력

In [3]:
df_stocks = pd.read_csv('stocks.csv')

In [4]:
df_stocks.head(1)

,Code,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,005930,삼성전자,KOSPI,NaN,54200,1,100,0.18,53500,54600,53300,12626235,680246198500,323562214210000,5969782550,STK,통신 및 방송 장비 제조업,"통신 및 방송 장비 제조(무선) 제품, 반도체 제조(메모리) 제품, 전자부품 제조(...",1975-06-11,12월,한종희,http://www.samsung.com/sec,경기도

In [11]:
df_stocks.index[df_stocks['ChagesRatio'] == 30]

Index([1232, 2018], dtype='int64')

#### 행추출 방법

In [12]:
# 행추출 방법
# 1. [] : 대괄호 접근
# df_stocks[df_stocks['ChagesRatio'] == 30]
# 2. loc : 인덱스명
# df_stocks.loc[df_stocks['ChagesRatio'] == 30]
# 3. iloc : 인덱스번호
indices = df_stocks.index[df_stocks['ChagesRatio'] == 30]
df_stocks.iloc[indices]
# 4. query
# df_stocks.query('ChagesRatio == 30')

,Code,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
1232,050960,수산아이앤티,KOSDAQ,벤처기업부,15860,4,3660,30.0,11000,15860,10640,950437,13732652520,107070860000,6751000,KSQ,소프트웨어 개발 및 공급업,"공유단말접속관리서비스, 보안솔루션 등",2016-10-11,12월,정은아,http://www.soosanint.co.kr,서울특별시
2018,121850,코이즈,KOSDAQ,벤처기업부,1495,4,345,30.0,1140,1495,1067,4923010,6886680301,45768191625,30614175,KSQ,플라스틱제품 제조업,"보호필름, 도광판, 백코팅",2012-09-27,12월,조재형,http://www.koyj.co.kr,충청북도

#### 행을 추출한뒤 열을 추출방법

In [32]:
# 1. [] : 대괄호 접근
# df_stocks[df_stocks['ChagesRatio'] == 30][['Name','Sector']]
# 2. loc : 인덱스명
# df_stocks.loc[df_stocks['ChagesRatio'] == 30][['Name','Sector']]
# df_stocks.loc[df_stocks['ChagesRatio'] == 30,['Name','Sector']]
# 3. iloc : 인덱스번호
# indices = df_stocks.index[df_stocks['ChagesRatio'] == 30]
# df_stocks.iloc[indices]
# df_stocks.iloc[df_stocks.index[df_stocks['ChagesRatio'] == 30]][['Name','Sector']]
# df_stocks.iloc[df_stocks.index[df_stocks['ChagesRatio'] == 30], [1,16]]
# 4. query
df_stocks.query('ChagesRatio == 30')[['Name','Sector']]

        Name          Sector
1232  수산아이앤티  소프트웨어 개발 및 공급업
2018     코이즈      플라스틱제품 제조업

#### 정렬하기

In [ ]:
# 전일 대비 상승률 상위 30위 종목
top_30_increse_indices =df_stocks.sort_values('ChagesRatio',ascending=False).head(30).index
df_top_30_increse = df_stocks.iloc[top_30_increse_indices]
df_top_30_increse

In [ ]:
# 전일 대비 상승률 하위 30위 종목
bottom_30_increse_indices =df_stocks.sort_values('ChagesRatio',ascending=True).head(30).index
df_bottom_30_increse = df_stocks.iloc[bottom_30_increse_indices]
df_bottom_30_increse

In [ ]:
# 전일 대비 상승률 상위 30위 종목
# 업종
# df_top_30_increse['Sector'].value_counts()
df_bottom_30_increse['Sector'].value_counts()

In [39]:
df_stocks.index

RangeIndex(start=0, stop=2855, step=1)

#### 그룹핑

In [51]:
df_stocks.groupby('Sector')[['Marcap','Volume']].mean()

                           Marcap         Volume
Sector
1차 비철금속 제조업          1.696958e+12  199535.857143
1차 철강 제조업            5.619208e+11  317216.661290
가구 제조업               1.705150e+11  246012.555556
가전제품 및 정보통신장비 소매업    1.666704e+11   10623.000000
가정용 기기 제조업           4.119952e+11   85266.444444
...                           ...            ...
항공기,우주선 및 부품 제조업     2.145873e+12  188238.000000
해상 운송업               3.097674e+12  678054.500000
해체, 선별 및 원료 재생업      5.312056e+10  263937.000000
화학섬유 제조업             3.873727e+11   55822.444444
회사 본부 및 경영 컨설팅 서비스업  2.854154e+11   41787.750000

[160 rows x 2 columns]

In [68]:
# 산업별 시가총액이 가장 큰 종목가져오기
pd.set_option('display.max_rows', None)  # None으로 설정하면 모든 행 출력
tmp_idx = df_stocks.groupby('Sector')[['Marcap']].idxmax()
df_stocks.loc[tmp_idx['Marcap'].values][['Sector','Industry','Name','Marcap']].sort_values('Marcap',ascending=False).head(20)

,Sector,Industry,Name,Marcap
0,통신 및 방송 장비 제조업,"통신 및 방송 장비 제조(무선) 제품, 반도체 제조(메모리) 제품, 전자부품 제조(...",삼성전자,323562214210000
1,반도체 제조업,"반도체,컴퓨터,통신기기 제조,도매",SK하이닉스,123323600631000
2,일차전지 및 이차전지 제조업,"2차전지 (소형,ESS,자동차전지)",LG에너지솔루션,91845000000000
3,기초 의약물질 제조업,바이오의약품,삼성바이오로직스,68184692000000
4,자동차용 엔진 및 자동차 제조업,"자동차(승용차,버스,트럭,특장차),자동차부품,자동차전착도료 제조,차량정비사업",현대차,42197362486500
8,기타 금융업,-,KB금융,32466094897500
9,"자료처리, 호스팅, 포털 및 기타 인터넷 정보매개 서비스업",포털 서비스 및 온라인 광고,NAVER,31925057112000
10,1차 비철금속 제조업,"연,아연괴 제조,판매",고려아연,31386177028000
12,자동차 신품 부품 제조업,"자동차A/S용 부품,컨테이너,특수중기,산업기계제품 생산,판매,부품모듈화,부품수출사업...",현대모비스,22411817654000
13,1차 철강 제조업,"열연코일,냉연강판,후판,선재,스테인리스 제조",POSCO홀딩스,21193152700500
14,기타 전문 도매업,"도소매, 건설, 남자용 정장 제조업 등",삼성물산,20854075751100
15,보험업,"생명보험,부동산 임대",삼성생명,19840000000000
18,선박 및 보트 건조업,"선박, 해양플랜트 및 엔진기계 등",HD현대중공업,18775514034000
19,기초 화학물질 제조업,"유화/기능/합성수지,재생섬유소,산업재,리튬이온전지,평광판,PVC 제조,도매",LG화학,17612789578500
22,석유 정제품 제조업,"석유정제,석유화학제품,윤활유제품,아스팔트제품,의약중간체 제조,판매,유전개발,대체에너지사업",SK이노베이션,16477894061600
24,해상 운송업,"정기,부정기,전용선,콘테이너선,자동차선,LNG선 해운",HMM,15735365398560
25,자연과학 및 공학 연구개발업,바이오시밀러 및 바이오베터,알테오젠,15435800706000
26,담배 제조업,"잎담배,제조담배,홍삼,홍삼제품 제조,판매",KT&G,15116800892100
27,소프트웨어 개발 및 공급업,<배틀그라운드> 등 게임 소프트웨어,크래프톤,14561786960000
29,전기업,"전력자원개발,발전,송전,전력용기자재확보",한국전력,13513343820850

In [ ]:
dir(df_stocks.groupby('Sector')['Marcap'])

In [96]:
df_stocks.groupby('Sector')['Marcap'].sum()

Sector
1차 비철금속 제조업            42025679933262
1차 철강 제조업              36062504736190
가구 제조업                  1579352329179
가전제품 및 정보통신장비 소매업        173044528960
가정용 기기 제조업              3750559291419
                            ...
항공기,우주선 및 부품 제조업       20223759888903
해상 운송업                 18821548038885
해체, 선별 및 원료 재생업           52393434311
화학섬유 제조업                3602587510624
회사 본부 및 경영 컨설팅 서비스업     3497612924040
Name: Marcap, Length: 160, dtype: int64

In [62]:
df_stocks.groupby('Sector')['Marcap'].sum().reset_index()

                  Sector          Marcap
0            1차 비철금속 제조업  42025679933262
1              1차 철강 제조업  36062504736190
2                 가구 제조업   1579352329179
3      가전제품 및 정보통신장비 소매업    173044528960
4             가정용 기기 제조업   3750559291419
..                   ...             ...
155     항공기,우주선 및 부품 제조업  20223759888903
156               해상 운송업  18821548038885
157      해체, 선별 및 원료 재생업     52393434311
158             화학섬유 제조업   3602587510624
159  회사 본부 및 경영 컨설팅 서비스업   3497612924040

[160 rows x 2 columns]

In [67]:
df_stocks.groupby('Sector')['Marcap'].idxmax()

Sector
1차 비철금속 제조업               7
1차 철강 제조업                13
가구 제조업                  413
가전제품 및 정보통신장비 소매업       868
가정용 기기 제조업              140
                       ...
항공기,우주선 및 부품 제조업         30
해상 운송업                   25
해체, 선별 및 원료 재생업        1927
화학섬유 제조업                248
회사 본부 및 경영 컨설팅 서비스업     294
Name: Marcap, Length: 160, dtype: int64

In [ ]:
# 산업별 시가총액 상위목록
print(df_stocks.columns)

# 산업별 시가 총액 합계 계산
grouped = df_stocks.groupby('Sector')['Marcap'].sum().reset_index()

# 각 산업별로 시가총액이 가장 높은 기업 찾기
top_industries = df_stocks.loc[df_stocks.groupby('Sector')['Marcap'].idxmax()]

top_industries