In [1]:
import numpy as np
import pandas as pd

In [3]:
df_stocks = pd.read_excel('stocks.xlsx')

In [4]:
df_stocks.shape

(2856, 21)

In [5]:
df_stocks.head(1)

,Code,Name,Market,Close,Changes,ChagesRatio,Open,High,Low,Volume,...,Marcap,Stocks,MarketId,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,005930,삼성전자,KOSPI,53700,600,1.13,53200,54400,53200,23525203,...,320577322935000,5969782550,STK,통신 및 방송 장비 제조업,"통신 및 방송 장비 제조(무선) 제품, 반도체 제조(메모리) 제품, 전자부품 제조(...",1975-06-11,12월,한종희,http://www.samsung.com/sec,경기도

In [6]:
df_stocks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2856 entries, 0 to 2855
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Code            2856 non-null   object
 1   Name            2856 non-null   object
 2   Market          2856 non-null   object
 3   Close           2856 non-null   int64
 4   Changes         2856 non-null   int64
 5   ChagesRatio     2856 non-null   float64
 6   Open            2856 non-null   int64
 7   High            2856 non-null   int64
 8   Low             2856 non-null   int64
 9   Volume          2856 non-null   int64
 10  Amount          2856 non-null   int64
 11  Marcap          2856 non-null   int64
 12  Stocks          2856 non-null   int64
 13  MarketId        2856 non-null   object
 14  Sector          2740 non-null   object
 15  Industry        2725 non-null   object
 16  ListingDate     2740 non-null   datetime64[ns]
 17  SettleMonth     2740 non-null   object
 18  Representative  2740 non-null   object
 19  HomePage        2548 non-null   object
 20  Region          2740 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(9), object(10)
memory usage: 468.7+ KB

In [7]:
df_stocks.describe()

,Close,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,ListingDate
count,2.856000e+03,2856.000000,2856.000000,2.856000e+03,2.856000e+03,2.856000e+03,2.856000e+03,2.856000e+03,2.856000e+03,2.856000e+03,2740
mean,1.752967e+04,-70.822129,-1.126744,1.743018e+04,1.781127e+04,1.698058e+04,4.401053e+05,5.452925e+09,8.184680e+11,4.187967e+07,2008-05-14 00:52:33.284671488
min,4.000000e+00,-34500.000000,-29.950000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.906666e+07,2.000000e+05,1956-03-03 00:00:00
25%,2.078750e+03,-160.000000,-2.580000,2.015000e+03,2.035000e+03,1.990750e+03,1.489350e+04,6.187578e+07,4.189281e+10,1.017354e+07,2000-08-24 00:00:00
50%,4.900000e+03,-36.000000,-1.030000,4.787500e+03,4.850000e+03,4.635000e+03,6.001450e+04,2.833065e+08,9.139148e+10,1.978120e+07,2010-12-18 12:00:00
75%,1.295250e+04,0.000000,0.000000,1.293500e+04,1.314000e+04,1.248000e+04,1.996052e+05,1.356889e+09,2.296312e+11,4.196432e+07,2019-08-09 12:00:00
max,2.000000e+06,329000.000000,33.330000,1.731000e+06,2.000000e+06,1.711000e+06,5.643993e+07,1.267526e+12,3.205773e+14,5.969783e+09,2024-11-29 00:00:00
std,5.804736e+04,6341.046588,3.779517,5.536307e+04,5.895708e+04,5.435167e+04,2.253159e+06,3.496820e+10,7.266422e+12,1.327896e+08,NaN